version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/cpg_crawler
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AI_PROVIDER=${AI_PROVIDER}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_CLAUDE_MODEL=${AWS_CLAUDE_MODEL}
      - USE_AWS_CLAUDE=${USE_AWS_CLAUDE}
      - USE_PROXY=${USE_PROXY}
      - PROXY_URL=${PROXY_URL}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - SAVE_SCREENSHOTS=${SAVE_SCREENSHOTS}
      - SCREENSHOT_PATH=${SCREENSHOT_PATH}
      - NAVIGATION_TIMEOUT=${NAVIGATION_TIMEOUT}
      - MAX_RETRIES=${MAX_RETRIES}
      - USER_AGENT=${USER_AGENT}
      - MAX_CONCURRENT_TASKS=${MAX_CONCURRENT_TASKS}
      - QUEUE_RETRY_DELAY=${QUEUE_RETRY_DELAY}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - cpg-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cpg-network

volumes:
  mongodb_data:

networks:
  cpg-network:
    driver: bridge 